/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AllListsRouteImport } from './routes/all-lists'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultResultIdRouteImport } from './routes/result/$resultId'
import { Route as AuthedProfileRouteImport } from './routes/_authed/profile'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ListUseListIdRouteImport } from './routes/list/use/$listId'
import { Route as ListEditListIdRouteImport } from './routes/list/edit/$listId'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AllListsRoute = AllListsRouteImport.update({
  id: '/all-lists',
  path: '/all-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultResultIdRoute = ResultResultIdRouteImport.update({
  id: '/result/$resultId',
  path: '/result/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListUseListIdRoute = ListUseListIdRouteImport.update({
  id: '/list/use/$listId',
  path: '/list/use/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListEditListIdRoute = ListEditListIdRouteImport.update({
  id: '/list/edit/$listId',
  path: '/list/edit/$listId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-lists': typeof AllListsRoute
  '/logout': typeof LogoutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof AuthedProfileRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/list/edit/$listId': typeof ListEditListIdRoute
  '/list/use/$listId': typeof ListUseListIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-lists': typeof AllListsRoute
  '/logout': typeof LogoutRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/profile': typeof AuthedProfileRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/list/edit/$listId': typeof ListEditListIdRoute
  '/list/use/$listId': typeof ListUseListIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/all-lists': typeof AllListsRoute
  '/logout': typeof LogoutRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/list/edit/$listId': typeof ListEditListIdRoute
  '/list/use/$listId': typeof ListUseListIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/all-lists'
    | '/logout'
    | '/login'
    | '/signup'
    | '/profile'
    | '/result/$resultId'
    | '/list/edit/$listId'
    | '/list/use/$listId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/all-lists'
    | '/logout'
    | '/login'
    | '/signup'
    | '/profile'
    | '/result/$resultId'
    | '/list/edit/$listId'
    | '/list/use/$listId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/all-lists'
    | '/logout'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_authed/profile'
    | '/result/$resultId'
    | '/list/edit/$listId'
    | '/list/use/$listId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AllListsRoute: typeof AllListsRoute
  LogoutRoute: typeof LogoutRoute
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
  ResultResultIdRoute: typeof ResultResultIdRoute
  ListEditListIdRoute: typeof ListEditListIdRoute
  ListUseListIdRoute: typeof ListUseListIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-lists': {
      id: '/all-lists'
      path: '/all-lists'
      fullPath: '/all-lists'
      preLoaderRoute: typeof AllListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$resultId': {
      id: '/result/$resultId'
      path: '/result/$resultId'
      fullPath: '/result/$resultId'
      preLoaderRoute: typeof ResultResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/use/$listId': {
      id: '/list/use/$listId'
      path: '/list/use/$listId'
      fullPath: '/list/use/$listId'
      preLoaderRoute: typeof ListUseListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/edit/$listId': {
      id: '/list/edit/$listId'
      path: '/list/edit/$listId'
      fullPath: '/list/edit/$listId'
      preLoaderRoute: typeof ListEditListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AllListsRoute: AllListsRoute,
  LogoutRoute: LogoutRoute,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
  ResultResultIdRoute: ResultResultIdRoute,
  ListEditListIdRoute: ListEditListIdRoute,
  ListUseListIdRoute: ListUseListIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
